# Generated by Django 4.1.2 on 2022-11-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottigliadb',
            name='img',
            field=models.CharField(default='images/Vino-stock.jpg', max_length=70),
        ),
    ]
