# Generated by Django 4.1.2 on 2022-11-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_bottigliadb_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottigliadb',
            name='img',
            field=models.CharField(default='images/Vino-stock.jpg', max_length=70, null=True),
        ),
    ]
