# Generated by Django 4.1.2 on 2022-11-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_remove_bottigliadb_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottigliadb',
            name='img',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
