# Generated by Django 4.1.2 on 2022-11-09 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_bottigliadb_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottigliadb',
            name='img',
        ),
    ]
