# Generated by Django 4.1.2 on 2022-11-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_remove_bottigliadb_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottigliadb',
            name='img',
            field=models.ImageField(blank=True, upload_to='files/images'),
        ),
    ]
