# Generated by Django 4.1.2 on 2022-11-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_bottigliadb_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('salario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='entradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='salidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='bottigliadb',
            name='img',
            field=models.ImageField(blank=True, upload_to='tiendaOnline/files/images'),
        ),
    ]
