# Generated by Django 4.1.2 on 2022-11-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_alter_bottigliadb_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='fechaInsercion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
