# Generated by Django 4.1.2 on 2022-12-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avatar',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
    ]
