# Generated by Django 4.1.2 on 2022-12-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_avatar_descripcion_avatar_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
