# Generated by Django 4.1.2 on 2022-11-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
